### ISSUE TITLE
className and activeClassName props

### ISSUE THREAD

**Issue by ryansrofe** [brohlson/gatsby-plugin-anchor-links#2]
This Gatsby plugin is really nice however, classes, id's, active classes, etc cannot be defined or attached like a Gatsby Link or href. This results in awesome functionality that needs workarounds to style properly. Maybe I'm missing something?

Also if you are having issues getting the plugin to work on other pages try adding the offset in the config. This immediately made this feature work for me. Without the offset in the config, it would not work on my other pages.

**Comment by brohlson** [comment]
Added to roadmap for v1.1.0
https://github.com/brohlson/gatsby-plugin-anchor-links/projects/1#card-32807929

As I mentioned in the other issue, if there is no offset, you technically won't notice anything happening because as of now, all the hashed links send browsers straight to the hashed section.  I'm playing around with a `stripHash` prop that will optionally force scrolls from top to selector on every route change.

**Comment by brohlson** [comment]
`activeClassName` at the page level can be targeted with `[aria-current]='page'` like any gatsby-link - I don't have plans to make active hash detection a priority at the moment.

**Comment by bstrokevin** [comment]
Any update on className? Would like to use it on my site.

**Comment by brohlson** [comment]
> Any update on className? Would like to use it on my site.

I haven't had much time in the past week to work on this.  However, it should be pretty easy to target these with parent selectors:

```javascript
<div class="foo">
    <AnchorLink ...props />
</div>
```
```css
.foo a { color: blue; }
```

**Comment by brohlson** [comment]
classNames added in https://github.com/brohlson/gatsby-plugin-anchor-links/pull/3

**Comment by oidualc** [comment]
> activeClassName at the page level can be targeted with [aria-current]='page' like any gatsby-link - I don't have plans to make active hash detection a priority at the moment.

How should it be used in this context?
